import { CATEGORIES, getCategory } from "@/constants/categories";
import { formatDate, formatMoney } from "@/lib/format";
import type { Expense } from "@/types/expense";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export type ReportData = {
  title: string;
  subtitle: string;
  expenses: Expense[];
  budget?: number | null;
};

export function buildReportHtml({
  title,
  subtitle,
  expenses,
  budget,
}: ReportData): string {
  const total = expenses.reduce((sum, e) => sum + e.amount, 0);

  const catTotals = new Map<string, number>();
  for (const e of expenses) {
    catTotals.set(e.category, (catTotals.get(e.category) ?? 0) + e.amount);
  }
  const byCategory = CATEGORIES.map((c) => ({
    cat: c,
    amount: catTotals.get(c.key) ?? 0,
  }))
    .filter((x) => x.amount > 0)
    .sort((a, b) => b.amount - a.amount);

  const sorted = [...expenses].sort(
    (a, b) => b.date - a.date || b.createdAt - a.createdAt
  );

  const budgetKpis =
    budget != null
      ? `<div class="kpi"><span>Budget</span><strong>${formatMoney(budget)}</strong></div>
         <div class="kpi"><span>${total > budget ? "Over budget" : "Remaining"}</span>
           <strong class="${total > budget ? "over" : "under"}">${formatMoney(
             Math.abs(budget - total)
           )}</strong></div>`
      : "";

  const catRows = byCategory
    .map(
      ({ cat, amount }) =>
        `<tr><td>${cat.icon} ${cat.label}</td><td class="num">${
          total > 0 ? Math.round((amount / total) * 100) : 0
        }%</td><td class="num">${formatMoney(amount)}</td></tr>`
    )
    .join("");

  const expenseRows = sorted
    .map(
      (e) =>
        `<tr><td>${formatDate(e.date)}</td><td>${getCategory(
          e.category
        ).label}</td><td>${escapeHtml(e.note ?? "")}</td><td class="num">${formatMoney(
          e.amount
        )}</td></tr>`
    )
    .join("");

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<style>
  * { box-sizing: border-box; }
  body { font-family: -apple-system, Roboto, Helvetica, sans-serif; color: #1A1A2E; margin: 0; padding: 32px; }
  header { border-bottom: 3px solid #208AEF; padding-bottom: 16px; margin-bottom: 24px; }
  h1 { font-size: 26px; margin: 0; }
  .subtitle { color: #8A8A9E; font-size: 14px; margin: 4px 0 0; }
  .summary { display: flex; flex-wrap: wrap; gap: 12px; margin-bottom: 28px; }
  .kpi { flex: 1; min-width: 120px; background: #F5F6FA; border-radius: 12px; padding: 14px 16px; }
  .kpi span { display: block; color: #8A8A9E; font-size: 12px; font-weight: 600; }
  .kpi strong { font-size: 20px; }
  .kpi .over { color: #E74C3C; }
  .kpi .under { color: #2ECC71; }
  h2 { font-size: 16px; margin: 24px 0 10px; }
  table { width: 100%; border-collapse: collapse; font-size: 13px; }
  th { text-align: left; color: #8A8A9E; font-size: 11px; text-transform: uppercase; padding: 8px 10px; border-bottom: 2px solid #ECECF2; }
  td { padding: 9px 10px; border-bottom: 1px solid #F0F0F5; }
  .num { text-align: right; white-space: nowrap; }
  .empty { color: #8A8A9E; font-style: italic; }
  footer { margin-top: 32px; color: #B0B0BE; font-size: 11px; text-align: center; }
</style>
</head>
<body>
  <header>
    <h1>${escapeHtml(title)}</h1>
    <p class="subtitle">${escapeHtml(subtitle)}</p>
  </header>

  <section class="summary">
    <div class="kpi"><span>Total spent</span><strong>${formatMoney(total)}</strong></div>
    <div class="kpi"><span>Entries</span><strong>${expenses.length}</strong></div>
    ${budgetKpis}
  </section>

  ${
    byCategory.length
      ? `<h2>By category</h2>
  <table>
    <thead><tr><th>Category</th><th class="num">Share</th><th class="num">Amount</th></tr></thead>
    <tbody>${catRows}</tbody>
  </table>`
      : ""
  }

  <h2>Expenses</h2>
  ${
    sorted.length
      ? `<table>
    <thead><tr><th>Date</th><th>Category</th><th>Note</th><th class="num">Amount</th></tr></thead>
    <tbody>${expenseRows}</tbody>
  </table>`
      : `<p class="empty">No expenses in this range.</p>`
  }

  <footer>Generated by Expense Tracker</footer>
</body>
</html>`;
}

/**
 * Renders the report HTML to a PDF in the cache directory and opens the share
 * sheet. Returns the file uri. Throws if PDF generation fails.
 */
export async function exportReportPdf(data: ReportData): Promise<string> {
  const html = buildReportHtml(data);
  const { uri } = await Print.printToFileAsync({ html });

  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, {
      mimeType: "application/pdf",
      UTI: "com.adobe.pdf",
      dialogTitle: "Share report",
    });
  }

  return uri;
}
